"""esquema inicial

Revision ID: 2d2720796d82
Revises:
Create Date: 2026-08-24 03:58:17.245599

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d2720796d82"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_question",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column(
            "discrepancy_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "tender_requirement", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "target_profile_field", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("answered", sa.Boolean(), nullable=False),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("omitted", sa.Boolean(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.Column(
            "target_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profile_question_answered"),
        "profile_question",
        ["answered"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_question_id"), "profile_question", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_profile_question_omitted"),
        "profile_question",
        ["omitted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_question_provider_id"),
        "profile_question",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_question_target_category"),
        "profile_question",
        ["target_category"],
        unique=False,
    )
    op.create_table(
        "region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tender_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tender_metadata_code"), "tender_metadata", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_tender_metadata_is_processed"),
        "tender_metadata",
        ["is_processed"],
        unique=False,
    )
    op.create_table(
        "tender_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tender_status_code"), "tender_status", ["code"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "buyer_institution",
        sa.Column("rut", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.PrimaryKeyConstraint("rut"),
    )
    op.create_table(
        "supplier",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("rut", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("legal_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trade_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("regions", sa.JSON(), nullable=True),
        sa.Column("sectors", sa.JSON(), nullable=True),
        sa.Column("certifications", sa.JSON(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("years_experience", sa.Integer(), nullable=True),
        sa.Column("num_employees", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("profile_changed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supplier_user_id"), "supplier", ["user_id"], unique=True)
    op.create_table(
        "tender",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("closing_at", sa.DateTime(), nullable=False),
        sa.Column("last_change_at", sa.DateTime(), nullable=False),
        sa.Column("buyer_rut", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buyer_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("available_amount_clp", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_rut"],
            ["buyer_institution.rut"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["tender_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tender_code"), "tender", ["code"], unique=True)
    op.create_table(
        "deep_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("compatibility_score", sa.Float(), nullable=False),
        sa.Column("recommendation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("justification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "prompt_instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tender.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tender_id", "supplier_id", name="uq_deep_analysis_tender_supplier"
        ),
    )
    op.create_index(
        op.f("ix_deep_analysis_supplier_id"),
        "deep_analysis",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deep_analysis_tender_id"), "deep_analysis", ["tender_id"], unique=False
    )
    op.create_table(
        "matching_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("reranker_score", sa.Float(), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tender.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supplier_id", "tender_id", name="uq_matching_result_supplier_tender"
        ),
    )
    op.create_index(
        op.f("ix_matching_result_supplier_id"),
        "matching_result",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "tender_ai_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_justification", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tender.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tender_id"),
    )
    op.create_table(
        "tender_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("product_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "unit_of_measure", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tender.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tender_item")
    op.drop_table("tender_ai_analysis")
    op.drop_index(op.f("ix_matching_result_supplier_id"), table_name="matching_result")
    op.drop_table("matching_result")
    op.drop_index(op.f("ix_deep_analysis_tender_id"), table_name="deep_analysis")
    op.drop_index(op.f("ix_deep_analysis_supplier_id"), table_name="deep_analysis")
    op.drop_table("deep_analysis")
    op.drop_index(op.f("ix_tender_code"), table_name="tender")
    op.drop_table("tender")
    op.drop_index(op.f("ix_supplier_user_id"), table_name="supplier")
    op.drop_table("supplier")
    op.drop_table("buyer_institution")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tender_status_code"), table_name="tender_status")
    op.drop_table("tender_status")
    op.drop_index(op.f("ix_tender_metadata_is_processed"), table_name="tender_metadata")
    op.drop_index(op.f("ix_tender_metadata_code"), table_name="tender_metadata")
    op.drop_table("tender_metadata")
    op.drop_table("region")
    op.drop_index(
        op.f("ix_profile_question_target_category"), table_name="profile_question"
    )
    op.drop_index(
        op.f("ix_profile_question_provider_id"), table_name="profile_question"
    )
    op.drop_index(op.f("ix_profile_question_omitted"), table_name="profile_question")
    op.drop_index(op.f("ix_profile_question_id"), table_name="profile_question")
    op.drop_index(op.f("ix_profile_question_answered"), table_name="profile_question")
    op.drop_table("profile_question")
    # ### end Alembic commands ###
