"""agrega provincia y comuna

Revision ID: 7df7c9a1ca0a
Revises: 01dffcf2bdbf
Create Date: 2026-08-31 18:39:31.755498

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7df7c9a1ca0a"
down_revision: str | Sequence[str] | None = "01dffcf2bdbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provincia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comuna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provincia_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provincia_id"],
            ["provincia.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "buyer_institution", sa.Column("comuna_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "buyer_institution",
        sa.Column(
            "comuna_resolution_source",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # Nombre explícito: a diferencia de `op.create_table(...)`, acá no hay
    # convención de nombres configurada que `op.f(None)` pueda resolver, y
    # `drop_constraint(None, ...)` en el downgrade falla en tiempo de
    # ejecución ("it has no name") si no se nombra acá.
    op.create_foreign_key(
        "fk_buyer_institution_comuna_id_comuna",
        "buyer_institution",
        "comuna",
        ["comuna_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_buyer_institution_comuna_id_comuna",
        "buyer_institution",
        type_="foreignkey",
    )
    op.drop_column("buyer_institution", "comuna_resolution_source")
    op.drop_column("buyer_institution", "comuna_id")
    op.drop_table("comuna")
    op.drop_table("provincia")
    # ### end Alembic commands ###
