"""create saved tender table

Revision ID: 82786321a8db
Revises: 2d2720796d82
Create Date: 2026-08-26 15:21:00.444956

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82786321a8db'
down_revision: str | Sequence[str] | None = '2d2720796d82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_tender',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', name='uq_saved_tender_user_tender')
    )
    op.create_index(op.f('ix_saved_tender_tender_id'), 'saved_tender', ['tender_id'], unique=False)
    op.create_index(op.f('ix_saved_tender_user_id'), 'saved_tender', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_tender_user_id'), table_name='saved_tender')
    op.drop_index(op.f('ix_saved_tender_tender_id'), table_name='saved_tender')
    op.drop_table('saved_tender')
    # ### end Alembic commands ###
