"""create tender chat tables

Revision ID: 869745767a10
Revises: 82786321a8db
Create Date: 2026-08-28 00:46:35.682326

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '869745767a10'
down_revision: str | Sequence[str] | None = '82786321a8db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_chat_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_chat_documents_tender_id'), 'tender_chat_documents', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_chat_documents_user_id'), 'tender_chat_documents', ['user_id'], unique=False)
    op.create_table('tender_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_chat_messages_tender_id'), 'tender_chat_messages', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_chat_messages_user_id'), 'tender_chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_chat_messages_user_id'), table_name='tender_chat_messages')
    op.drop_index(op.f('ix_tender_chat_messages_tender_id'), table_name='tender_chat_messages')
    op.drop_table('tender_chat_messages')
    op.drop_index(op.f('ix_tender_chat_documents_user_id'), table_name='tender_chat_documents')
    op.drop_index(op.f('ix_tender_chat_documents_tender_id'), table_name='tender_chat_documents')
    op.drop_table('tender_chat_documents')
    # ### end Alembic commands ###
