"""columnas hdu 05.2 en tender_chat_messages

Revision ID: c952eb0506d2
Revises: 7df7c9a1ca0a
Create Date: 2026-09-02 00:55:25.413173

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c952eb0506d2'
down_revision: str | Sequence[str] | None = '9809f07342d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_chat_messages', sa.Column('discrepancies', sa.JSON(), nullable=True))
    op.add_column('tender_chat_messages', sa.Column('warnings', sa.JSON(), nullable=True))
    op.add_column('tender_chat_messages', sa.Column('unbacked_aspects', sa.JSON(), nullable=True))
    # `server_default` es imprescindible: la columna es NOT NULL y la tabla ya
    # tiene mensajes de las HdU 04 y 05.1 en las bases de datos del equipo. Sin
    # un valor por defecto, el ALTER TABLE falla sobre esas filas. Se retira
    # enseguida porque el valor lo aporta la aplicación en cada inserción; el
    # default solo existe para poblar el histórico.
    op.add_column(
        'tender_chat_messages',
        sa.Column('has_sufficient_info', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('tender_chat_messages', 'has_sufficient_info', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_chat_messages', 'has_sufficient_info')
    op.drop_column('tender_chat_messages', 'unbacked_aspects')
    op.drop_column('tender_chat_messages', 'warnings')
    op.drop_column('tender_chat_messages', 'discrepancies')
    # ### end Alembic commands ###
