"""borradores de postulacion (HU-20, B1)

Una tabla nueva, `proposal_drafts`: un borrador por empresa y licitación, con
restricción única (`supplier_id`, `tender_id`). No toca ninguna existente, así
que la versión vieja convive con este esquema durante el despliegue.

Exigencias, decisiones, advertencias y contenido van en JSONB: se leen y
escriben siempre junto con el borrador y ninguna consulta filtra por ellos.
`status` es texto con CHECK y no ENUM, para que sumar un estado no exija un
`ALTER TYPE`. "Vencido" no es un estado: se calcula al leer.

RLS: en producción lo activa el event trigger `ensure_rls` del panel de
Supabase al crear la tabla, no esta migración.

Revision ID: e4849ff0c0dd
Revises: 1974cf871a7d
Create Date: 2026-09-30 16:16:01.658444

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4849ff0c0dd"
down_revision: str | Sequence[str] | None = "1974cf871a7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "paused_requirement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("requires_technical_document", sa.Boolean(), nullable=False),
        sa.Column(
            "technical_document_reason",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "discrepancy_decisions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "last_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('FEASIBILITY', 'PAUSED', 'STOPPED', 'READY')",
            name="ck_proposal_drafts_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tender.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supplier_id", "tender_id", name="uq_proposal_drafts_supplier_tender"
        ),
    )
    op.create_index(
        op.f("ix_proposal_drafts_created_by_user_id"),
        "proposal_drafts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proposal_drafts_tender_id"),
        "proposal_drafts",
        ["tender_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposal_drafts_tender_id"), table_name="proposal_drafts")
    op.drop_index(
        op.f("ix_proposal_drafts_created_by_user_id"), table_name="proposal_drafts"
    )
    op.drop_table("proposal_drafts")
    # ### end Alembic commands ###
