"""banco de capacidades y evidencias (HU-20, B0a)

Tres tablas nuevas; no toca ninguna existente, así que la versión vieja convive
sin problema con este esquema durante el despliegue:

* `capability_question`: banco de preguntas compartido entre empresas.
* `capability_answer`: la respuesta de cada empresa, con quién respondió y su
  vigencia.
* `capability_evidence`: proyectos que respaldan la experiencia de una empresa.
  `answer_id` es nullable desde ya para admitir evidencias importadas de
  Mercado Público sin otra migración (plan 230, §2.1).

Rescata el diseño de la migración `d9d22b5370ff` de la rama
`230-hu-20-1-banco-de-capacidades`, que nunca se subió, pero **sin** sembrar
preguntas ni recuperar respuestas desde `supplier.keywords`: `profile_question`
y el banner del home siguen como están, y migrarlos es una issue aparte
(plan 230, §5 punto 8).

RLS: en producción lo activa el event trigger `ensure_rls` del panel de
Supabase al crear cada tabla, no esta migración.

Revision ID: eead2dba418a
Revises: ea51f4f30556
Create Date: 2026-09-30 12:18:02.447347

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eead2dba418a"
down_revision: str | Sequence[str] | None = "ea51f4f30556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capability_question",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_field", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("work_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('capacidad', 'certificacion', 'experiencia_proyecto')",
            name="ck_capability_question_kind",
        ),
        sa.CheckConstraint(
            "origin IN ('semilla', 'ia')", name="ck_capability_question_origin"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category", "target_field", name="uq_capability_question_category_field"
        ),
    )
    op.create_table(
        "capability_answer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("answered", sa.Boolean(), nullable=False),
        sa.Column("omitted", sa.Boolean(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=True),
        sa.Column("answered_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "NOT (answered AND omitted)", name="ck_capability_answer_estado"
        ),
        sa.ForeignKeyConstraint(
            ["answered_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["capability_question.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tender.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supplier_id", "question_id", name="uq_capability_answer_supplier_question"
        ),
    )
    op.create_index(
        op.f("ix_capability_answer_answered_by_user_id"),
        "capability_answer",
        ["answered_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_answer_question_id"),
        "capability_answer",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_answer_tender_id"),
        "capability_answer",
        ["tender_id"],
        unique=False,
    )
    op.create_table(
        "capability_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=True),
        sa.Column("work_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buyer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("amount_clp", sa.BigInteger(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "origin IN ('manual', 'mercado_publico')",
            name="ck_capability_evidence_origin",
        ),
        sa.CheckConstraint(
            "amount_clp IS NULL OR amount_clp >= 0",
            name="ck_capability_evidence_amount",
        ),
        sa.CheckConstraint("year >= 1900", name="ck_capability_evidence_year"),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["capability_answer.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capability_evidence_answer_id"),
        "capability_evidence",
        ["answer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_evidence_created_by_user_id"),
        "capability_evidence",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_evidence_supplier_id"),
        "capability_evidence",
        ["supplier_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_capability_evidence_supplier_id"), table_name="capability_evidence"
    )
    op.drop_index(
        op.f("ix_capability_evidence_created_by_user_id"),
        table_name="capability_evidence",
    )
    op.drop_index(
        op.f("ix_capability_evidence_answer_id"), table_name="capability_evidence"
    )
    op.drop_table("capability_evidence")
    op.drop_index(
        op.f("ix_capability_answer_tender_id"), table_name="capability_answer"
    )
    op.drop_index(
        op.f("ix_capability_answer_question_id"), table_name="capability_answer"
    )
    op.drop_index(
        op.f("ix_capability_answer_answered_by_user_id"), table_name="capability_answer"
    )
    op.drop_table("capability_answer")
    op.drop_table("capability_question")
    # ### end Alembic commands ###
