"""tablero-kanban

Revision ID: fa511ba1ba22
Revises: 5d0cd7e936db
Create Date: 2026-09-20 22:46:41.318382

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa511ba1ba22'
down_revision: str | Sequence[str] | None = '5d0cd7e936db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_column',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanban_column_user_id'), 'kanban_column', ['user_id'], unique=False)
    op.create_table('kanban_card',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['kanban_column.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', name='uq_kanban_card_user_tender')
    )
    op.create_index(op.f('ix_kanban_card_column_id'), 'kanban_card', ['column_id'], unique=False)
    op.create_index(op.f('ix_kanban_card_tender_id'), 'kanban_card', ['tender_id'], unique=False)
    op.create_index(op.f('ix_kanban_card_user_id'), 'kanban_card', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kanban_card_user_id'), table_name='kanban_card')
    op.drop_index(op.f('ix_kanban_card_tender_id'), table_name='kanban_card')
    op.drop_index(op.f('ix_kanban_card_column_id'), table_name='kanban_card')
    op.drop_table('kanban_card')
    op.drop_index(op.f('ix_kanban_column_user_id'), table_name='kanban_column')
    op.drop_table('kanban_column')
    # ### end Alembic commands ###
