"""huella del analisis de postulacion (HU-20)

Una columna nullable, `proposal_drafts.analysis_fingerprint`: resume los adjuntos,
el perfil de la empresa y la ficha usados en la factibilidad. Al "volver a
analizar", si la huella no cambió, el borrador se mantiene en vez de descartarse.
Nullable y sin default: en Postgres es un cambio solo de catálogo, sin reescribir
la tabla. Los borradores anteriores quedan con NULL y se analizan de nuevo la
primera vez que se pida.

Revision ID: fd545819dc8b
Revises: e4849ff0c0dd
Create Date: 2026-10-01 03:41:14.610806

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel mapea `str` a `sqlmodel.sql.sqltypes.AutoString`, así que las
# migraciones autogeneradas lo referencian. Sin este import fallan con
# NameError al aplicarse.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd545819dc8b"
down_revision: str | Sequence[str] | None = "e4849ff0c0dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proposal_drafts",
        sa.Column(
            "analysis_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposal_drafts", "analysis_fingerprint")
    # ### end Alembic commands ###
